---
# WARNING:  the way the rr value here is crawled out of the response is potentially brittle af because of the -
# thanks acme guys and yaml parser writers.  

- debug:
    msg: "{{ dnschallenge.challenge_data_dns }}"

- name: putting the challenges we got for all domains into the DNS
  route53:
    aws_access_key: "{{ aws_key |default(omit) }}"
    aws_secret_key: "{{ aws_secret |default(omit) }}"
    zone: "{{ acmecnamezone | default(item.key.split('.', 1)[1]) }}"
    record: "{{ item.key }}.{{ acmecnamezone }}"
    type: TXT
    ttl: 60
    value: '"{{ item.value | first }}"'
    state: present
    overwrite: true
  delegate_to: localhost
  with_dict: "{{ dnschallenge.challenge_data_dns }}"
  when: dnschallenge.changed

- name: wait because
  wait_for:
    timeout: 61
  delegate_to: localhost
  when: dnschallenge.changed and dnschallenge.challenge_data_dns|length > 0
